/* prettier-ignore-start */
/* eslint-disable */
/* oxlint-disable */
/**
 * AUTO-GENERATED BY TAKO — DO NOT EDIT
 *
 * Regenerated by the Tako CLI on init, dev, deploy, `tako generate`, and
 * secrets changes. Manual edits will be overwritten on the next run.
 */

import "tako.sh";

/**
 * Environments available through `tako.env`, `process.env.ENV`, and `import.meta.env.ENV`.
 *
 * Generated from `[envs.*]` in `tako.toml`, with `development` and `production` always included.
 *
 * @example
 * ```ts
 * import { tako } from "tako.sh";
 *
 * if (tako.env === "production") {
 *   tako.logger.info("running in the selected environment");
 * }
 * ```
 */
export type Env = "development" | "production";

declare module "tako.sh" {
  export interface TakoTypeRegistry {
    /** Narrows the SDK's `Env` export to this project's configured environments. */
    Env: "development" | "production";
  }

  /**
   * Project-specific secret keys from `.tako/secrets.json`.
   *
   * No secrets are currently configured for this project. After you add one,
   * this interface is regenerated with typed readonly keys.
   */
  export interface TakoSecrets {}

  /**
   * Project-specific object storage bindings from `tako.toml`.
   *
   * No storages are currently configured for this project. After you add one,
   * this interface is regenerated with typed readonly bindings.
   */
  export interface TakoStorages {}

}

interface TakoUserEnv {}

/**
 * User-defined environment variables available on `process.env` and `import.meta.env`.
 *
 * Use `tako.sh` exports for Tako-provided runtime state such as env, port, build, and dataDir.
 */
declare global {
  namespace NodeJS {
    interface ProcessEnv extends TakoUserEnv {}
  }
  interface ImportMetaEnv extends TakoUserEnv {}
}
