// Code generated by errkit. DO NOT EDIT.

use std::fmt;

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum Err {
    /// WS first frame failed to parse as a tako.auth envelope.
    AuthFrameMalformed,
    /// WS header-auth channel did not receive an auth envelope within the required window.
    AuthFrameMissing,
    /// Channel name does not match any defined channel.
    ChannelUnknown,
    /// Query-string params failed JSON-Schema validation.
    ParamsInvalid,
    /// lastMessageId is older than the channel replay window.
    ReplayTooOld,
    /// The app's verify callback rejected the channel request.
    VerifyRejected,
}

impl Err {
    pub const ALL: &'static [Self] = &[
        Self::AuthFrameMalformed,
        Self::AuthFrameMissing,
        Self::ChannelUnknown,
        Self::ParamsInvalid,
        Self::ReplayTooOld,
        Self::VerifyRejected,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::AuthFrameMalformed => "PDS2Z5",
            Self::AuthFrameMissing => "47WJ38",
            Self::ChannelUnknown => "7RQYM3",
            Self::ParamsInvalid => "K5Q4D8",
            Self::ReplayTooOld => "YHNEN8",
            Self::VerifyRejected => "GJRQHR",
        }
    }

    pub fn from_code(code: &str) -> Option<Self> {
        match code {
            "PDS2Z5" => Some(Self::AuthFrameMalformed),
            "47WJ38" => Some(Self::AuthFrameMissing),
            "7RQYM3" => Some(Self::ChannelUnknown),
            "K5Q4D8" => Some(Self::ParamsInvalid),
            "YHNEN8" => Some(Self::ReplayTooOld),
            "GJRQHR" => Some(Self::VerifyRejected),
            _ => None,
        }
    }
}

impl AsRef<str> for Err {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl fmt::Display for Err {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::error::Error for Err {}
