/* prettier-ignore-start */
/* eslint-disable */
/* oxlint-disable */
/**
 * AUTO-GENERATED BY TAKO — DO NOT EDIT
 *
 * Regenerated by the Tako CLI on init, dev, deploy, `tako generate`, and
 * secrets changes. Manual edits will be overwritten on the next run.
 */

import "tako.sh";

/**
 * Environments available through `tako.env`, `process.env.ENV`, and `import.meta.env.ENV`.
 *
 * Generated from `[envs.*]` in `tako.toml`, with `development` and `production` always included.
 *
 * @example
 * ```ts
 * import { tako } from "tako.sh";
 *
 * if (tako.env === "production") {
 *   tako.logger.info("running in the selected environment");
 * }
 * ```
 */
export type Env = "development" | "production";

declare module "tako.sh" {
  export interface TakoTypeRegistry {
    /** Narrows the SDK's `Env` export to this project's configured environments. */
    Env: "development" | "production";
  }

  /**
   * Project-specific secret keys from `.tako/secrets.json`.
   *
   * No secrets are currently configured for this project. After you add one,
   * this interface is regenerated with typed readonly keys.
   */
  export interface TakoSecrets {}

  /**
   * Project-specific channel metadata discovered from `<app_root>/channels/`.
   *
   * Used by `tako.sh/client` and `tako.sh/react` to type route params, messages, and transports.
   */
  export interface TakoChannels {
    /** Channel `"mission-log"` route params, message metadata, and transport. */
    "mission-log": import("tako.sh").InferChannel<typeof import("./channels/mission-log").default>;
  }
}

/**
 * Tako-provided runtime environment variables available on `process.env` and `import.meta.env`.
 *
 * Values are strings because they come from the process environment.
 */
interface TakoRuntimeEnv {
  /** Current environment. Narrowed to `[envs.*]` declared in `tako.toml`. */
  readonly ENV: Env;
  /** Port Tako assigned to this app instance. */
  readonly PORT: string;
  /** Host/address Tako bound this app instance to. */
  readonly HOST: string;
  /** Build identifier injected by Tako at deploy time. `"dev"` under `tako dev`. */
  readonly TAKO_BUILD: string;
  /** Persistent app-owned data directory — writes survive restarts and deploys. */
  readonly TAKO_DATA_DIR: string;
}

declare global {
  namespace NodeJS {
    interface ProcessEnv extends TakoRuntimeEnv {}
  }
  interface ImportMetaEnv extends TakoRuntimeEnv {}
}
