/**
 * AUTO-GENERATED BY TAKO — DO NOT EDIT
 *
 * Regenerated by the Tako CLI on init, dev, deploy, `tako typegen`, and
 * secrets changes. Manual edits will be overwritten on the next run.
 */

import { createLogger, loadSecrets } from "tako.sh/runtime";

/**
 * Environments declared in `tako.toml` (plus `development` and `production`).
 * Use this anywhere you take an env name as input — TypeScript will reject
 * values that aren't in the union.
 *
 * @example
 * ```ts
 * import type { Env } from "../tako.gen";
 *
 * function featureFlag(flag: string, envs: readonly Env[]): boolean {
 *   return envs.includes(process.env.ENV);
 * }
 * ```
 */
export type Env = "development" | "production";

/**
 * Shape of the {@link secrets} export. One `readonly string` field per key in
 * `.tako/secrets.json`. Bulk serialization returns `"[REDACTED]"` so logging
 * the whole object by accident can't leak values.
 *
 * @example
 * ```ts
 * import { secrets } from "../tako.gen";
 *
 * const dbUrl = secrets.DATABASE_URL;     // typed string
 * console.log(secrets);                   // "[REDACTED]"
 * ```
 */
export interface Secrets {
  /** Secret `FOO` — injected by Tako at runtime. */
  readonly FOO: string;
  /** `String(secrets)` returns `"[REDACTED]"` to prevent accidental leaks. */
  toString(): "[REDACTED]";
  /** `JSON.stringify(secrets)` returns `"[REDACTED]"` to prevent accidental leaks. */
  toJSON(): "[REDACTED]";
}

/**
 * Augment `process.env` / `import.meta.env` with the vars Tako guarantees
 * are set on every spawned instance (both `tako deploy` and `tako dev`).
 * `process.env.ENV` is narrowed to the project's {@link Env} union; the
 * rest are always-defined strings.
 *
 * @example
 * ```ts
 * // With the augmentation, direct `process.env` reads are typed:
 * if (process.env.ENV === "production") startMetricsReporter();
 * const PORT = Number(process.env.PORT); // number, no `!` needed
 * ```
 */
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      /** Current environment. Narrowed to `[envs.*]` declared in `tako.toml`. */
      readonly ENV: Env;
      /** Port Tako assigned to this app instance. */
      readonly PORT: string;
      /** Host/address Tako bound this app instance to. */
      readonly HOST: string;
      /** Build identifier injected by Tako at deploy time. `"dev"` under `tako dev`. */
      readonly TAKO_BUILD: string;
      /** Persistent app-owned data directory — writes survive restarts and deploys. */
      readonly TAKO_DATA_DIR: string;
    }
  }
  interface ImportMetaEnv {
    /** Current environment. Narrowed to `[envs.*]` declared in `tako.toml`. */
    readonly ENV: Env;
    /** Port Tako assigned to this app instance. */
    readonly PORT: string;
    /** Host/address Tako bound this app instance to. */
    readonly HOST: string;
    /** Build identifier injected by Tako at deploy time. `"dev"` under `tako dev`. */
    readonly TAKO_BUILD: string;
    /** Persistent app-owned data directory — writes survive restarts and deploys. */
    readonly TAKO_DATA_DIR: string;
  }
}

/**
 * Tako populates `process.env` on the server — these accessors guard the
 * reads so importing `tako.gen.ts` from an isomorphic file (e.g. a
 * TanStack Start route or Next.js server component that also renders on
 * the client) does not throw `ReferenceError: process is not defined`.
 * Consumers that only read these in server-only code keep the same
 * types; client-side reads fall through to empty values.
 */
const __takoEnv: NodeJS.ProcessEnv =
  typeof process !== "undefined" && process.env
    ? process.env
    : ({} as NodeJS.ProcessEnv);

/**
 * Current environment. TypeScript narrows this against the project's
 * {@link Env} union, so `env === "staging"` is a compile error unless
 * `[envs.staging]` is declared in `tako.toml`.
 *
 * @example
 * ```ts
 * import { env } from "../tako.gen";
 *
 * switch (env) {
 *   case "production": return getProductionClient();
 *   case "development": return getMockClient();
 * }
 * ```
 */
export const env = __takoEnv.ENV;

/**
 * `true` when the app is running under `tako dev`.
 *
 * @example
 * ```ts
 * import { isDev } from "../tako.gen";
 *
 * const log = isDev ? console.log : () => {};
 * ```
 */
export const isDev = env === "development";

/**
 * `true` when the app is running under `tako deploy` in a production env.
 *
 * @example
 * ```ts
 * import { isProd, logger } from "../tako.gen";
 *
 * if (isProd) logger.info("request", { userId, path });
 * ```
 */
export const isProd = env === "production";

/**
 * Port Tako assigned to this app instance. Pass straight to your server.
 *
 * @example
 * ```ts
 * import { port, host } from "../tako.gen";
 *
 * Bun.serve({ port, hostname: host, fetch: handleRequest });
 * ```
 */
export const port = /* @__PURE__ */ Number(__takoEnv.PORT);

/** Host/address Tako bound this app instance to. */
export const host = __takoEnv.HOST;

/**
 * Build identifier. Production deploys use a content hash; `tako dev` uses
 * the literal string `"dev"`. Handy for cache keys and error reports.
 *
 * @example
 * ```ts
 * import { build } from "../tako.gen";
 *
 * Sentry.init({ release: build });
 * ```
 */
export const build = __takoEnv.TAKO_BUILD;

/**
 * Persistent app-owned data directory. Writes survive restarts and deploys —
 * ideal for SQLite files, uploaded assets, and long-lived caches.
 *
 * @example
 * ```ts
 * import { Database } from "bun:sqlite";
 * import { join } from "node:path";
 * import { dataDir } from "../tako.gen";
 *
 * const db = new Database(join(dataDir, "app.db"));
 * ```
 */
export const dataDir = __takoEnv.TAKO_DATA_DIR;

/** Directory the app is running from (`process.cwd()`). */
export const appDir = /* @__PURE__ */ (() =>
  typeof process !== "undefined" && typeof process.cwd === "function"
    ? process.cwd()
    : "")();

/**
 * Structured JSON logger bound to `source: "app"`. Emits one line per call
 * to stdout in a shape `tako dev` and production log pipelines understand.
 *
 * @example
 * ```ts
 * import { logger } from "../tako.gen";
 *
 * logger.info("user signed in", { userId, ip });
 * logger.error("payment failed", { orderId, err: String(err) });
 * ```
 */
export const logger = /* @__PURE__ */ createLogger("app");

/**
 * Tako-managed secrets, typed by the {@link Secrets} interface. Individual
 * lookups return the string value; bulk serialization is redacted.
 *
 * @example
 * ```ts
 * import { secrets } from "../tako.gen";
 *
 * const db = postgres(secrets.DATABASE_URL);
 *
 * console.log(secrets);            // "[REDACTED]"
 * JSON.stringify(secrets);         // "\"[REDACTED]\""
 * secrets.DATABASE_URL = "oops";   // compile error — readonly
 * ```
 */
export const secrets = /* @__PURE__ */ loadSecrets<Secrets>();

export interface TakoChannels {
  "mission-log": { params: { base: string; }; messages: Record<string, unknown>; transport: "sse"; };
}
