// Code generated by tako generate. DO NOT EDIT.
package main

import "tako.sh"

// Secrets provides type-safe access to Tako-managed secrets.
var Secrets = struct {
	ApiKey        func() string
	DatabaseUrl   func() string
	ExampleSecret func() string
}{
	ApiKey:        func() string { return tako.GetSecret("API_KEY") },
	DatabaseUrl:   func() string { return tako.GetSecret("DATABASE_URL") },
	ExampleSecret: func() string { return tako.GetSecret("EXAMPLE_SECRET") },
}
